# CASO PRÁCTICO

## Ejercicio 2

* Crea un array con la secuencia de números del 20 al 40 (ambos inclusive).
* Crea un array con la secuencia de números del 20 al 40 (ambos inclusive), tomados de 5 en 5 elementos.
* Muestra el array anterior en orden inverso.
* Si es posible intenta reconvertir el array reverso en un nuevo array multimensinal de 2x3, si no es posible agrega elementos al array hasta que la longitud del array sea divisible entre 3.
* Finalmente, elimina todas las dimensiones y devuelve un array plano.

### SOLUCIÓN

Generamos el primer array de 20 a 40

In [1]:
import numpy as np

first_array = np.arange(20, 40)
first_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

Recordamos que arange toma desde (inclusive), hasta (no inclusive), por lo tanto sumamos 1

In [2]:
first_array = np.arange(20, 40+1) # Equivalente 20, 41
first_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

Creamos una secuencia del array anterior de 5 en 5

In [3]:
sequence = first_array[::5]
sequence

array([20, 25, 30, 35, 40])

Mostramos el array en orden reverso

In [4]:
reverse_array = sequence[::-1]
reverse_array

array([40, 35, 30, 25, 20])

Reestructuramos el array para que sea de 2x3

In [5]:
new_dims = reverse_array.reshape(2,3)
new_dims

ValueError: cannot reshape array of size 5 into shape (2,3)

5 no es divisible entre 3, por lo tanto tenemos que agregar un nuevo elemento, para ello, una posible manera es crear un array con un nuevo elemento y concatenarlo al array existente.

In [6]:
aux = np.array([15])
aux

array([15])

In [7]:
new_dims = np.concatenate((reverse_array, aux))
new_dims

array([40, 35, 30, 25, 20, 15])

Obtenemos las nuevas dimensiones

In [8]:
new_dims = new_dims.reshape(2,3)
new_dims

array([[40, 35, 30],
       [25, 20, 15]])

Finalmente, obtenemos un array plano.

In [9]:
flat_array = new_dims.ravel()
flat_array

array([40, 35, 30, 25, 20, 15])