# CASO PRÁCTICO

## Ejercicio 1

* Escribe un array con 10 ceros.
* Escribe un array con 10 unos.
* Escribe un array con 10 sietes.

### SOLUCIÓN

Lo primero de todo, importamos la librería Numpy

In [1]:
import numpy as np

Creamos el array de ceros

In [2]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Creamos el array de unos

In [3]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Para el array de sietes no hay una función como np.sevens(), pero sabemos que una operación sobre un array afecta a todos sus elementos, por lo que si multiplicamos un array de unos por 7 obtendremos...

In [4]:
sevens = np.ones(10)*7
sevens

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])