# Exercise 1

We work for a store that has give to us the following table with the sales of different products
 
| Day | Bananas (quantity) | Apples (quantity) | Oranges (quantity) | Total amount |
| --- |  --- | --- | --- | --- |
| Monday | 5 | 32 | 16 | ? | 
| Tuesday | 8 | 25 | 14 | ? | 
| Wednesday | 12 | 15 | 15 | ? | 
| Thursday | 6 | 36 | 20 | ? | 
| Friday | 9 | 45 | 21 | ? | 
| Saturday | 4 | 22 | 25 | ? | 
| Sunday | 7 | 17 | 10 | ? | 

 
We don’t have the benefits of the store but, they give to us another table that shows the unit price for each vegetable.

| Fruit      |  unit price | 
| :---       |    :----:   | 
| Banana | 5 |
| Apple  | 2 |
| Orange | 3 |
 
With this, two tables try to obtain the following insights about the data:
 Get the total amount of the store multiplying each element with their own price.
Get the total of benefits
Get the total by each vegetable.
Get the mean of units sold by vegetable.
Get the mean of units sold by day.


In [1]:
import numpy as np

In [2]:
bananas = np.array([5, 8, 12, 6, 9, 4, 7])

In [3]:
apples = np.array([32, 25, 15, 36, 45, 22, 17])

In [4]:
oranges = np.array([16, 14, 15, 20, 21, 25, 10])

In [5]:
# First create the table with all the quantities
products_sold = np.concatenate([bananas, apples, oranges], 0).reshape(3, 7).T
products_sold

array([[ 5, 32, 16],
       [ 8, 25, 14],
       [12, 15, 15],
       [ 6, 36, 20],
       [ 9, 45, 21],
       [ 4, 22, 25],
       [ 7, 17, 10]])

In [6]:
# Create the table prices
prices = np.array([5, 3, 2])
prices

array([5, 3, 2])

In [7]:
total_amount = prices.dot(products_sold.T)

In [8]:
# Total amount by day
total_amount

array([153, 143, 135, 178, 222, 136, 106])

In [9]:
# We can check that (5*5 + 32*2 + 16*2) = 153

Total of benefits

In [10]:
total_amount.sum()

1073

Now, we are going to get the total amount by product

In [11]:
np.array(np.split(prices, 3))

array([[5],
       [3],
       [2]])

In [12]:
total_beneficts_day = np.array(np.split(prices, 3))*(products_sold.T)

In [13]:
total_beneficts_day.sum(axis=1)

array([255, 576, 242])

Get the mean of units sold by vegetable.

In [14]:
products_sold.mean(0)

array([ 7.28571429, 27.42857143, 17.28571429])

In [15]:
print("Mean of units sold of Bananas ", round(products_sold.mean(0)[0], 2))

Mean of units sold of Bananas  7.29


Get the mean of units sold by day.

In [16]:
products_sold.mean(1)

array([17.66666667, 15.66666667, 14.        , 20.66666667, 25.        ,
       17.        , 11.33333333])

In [17]:
print("Mean of units sold in Monday ", round(products_sold.mean(1)[0], 2))

Mean of units sold in Monday  17.67


# Exercise 2

Generate an array of 4 rows with the following restrictions:
* The first row must contains the numbers 6, 55, 12, 32, 20, 15
* The elements of the second row must be the first row *2
* The elements of the third row must be the second row -5
* The elements of the fourth row must be the square of the third row

After generate the array, filter it by only pair values


In [18]:
first_row = np.array([6, 55, 12, 32, 20, 15])
second_row = np.array(first_row) *2
third_row = np.array(second_row) -5 
fourth_row = np.array(third_row)**2

matrix = np.array([
    first_row,
    second_row,
    third_row,
    fourth_row
])

matrix

array([[    6,    55,    12,    32,    20,    15],
       [   12,   110,    24,    64,    40,    30],
       [    7,   105,    19,    59,    35,    25],
       [   49, 11025,   361,  3481,  1225,   625]])

In [19]:
# odd
matrix[(matrix % 2 != 0)]

array([   55,    15,     7,   105,    19,    59,    35,    25,    49,
       11025,   361,  3481,  1225,   625])

In [20]:
# pairs
matrix[(matrix % 2 != 1)]

array([  6,  12,  32,  20,  12, 110,  24,  64,  40,  30])

# Exercise 3

Solve the following system of linear equations
* x + (-7y) -z = 5
* 2x +y +6z = 12
* -x +2y -z = 6

Linear matrix equation are solved by the function linalg, find the correct function to solve the problem https://numpy.org/doc/stable/reference/routines.linalg.html

In [21]:
a = np.array([
    [1, -7, -1],
    [2, +1, +6],
    [-1, +2, -1]
])

# Independent term
b = np.array([5, 12, 6])

In [22]:
print("X, Y, Z values ",np.linalg.solve(a, b))

X, Y, Z values  [-41.9  -9.2  17.5]


# Exercise 4

* Create a 1-dimensional NumPy array using np.array(), check the number of dimensions with ndim
* Create a 2-dimensional NumPy array using np.array(), check the number of dimensions with ndim
* Create a 3-dimensional Numpy array using np.array(), check the number of dimensions with ndim
* Create an array of shape (7, 2, 3) of only zeros
* Create an array within a range of 0 and 100 with step 3
* Explore the random functions and create the following arrays
    * Create a random array with numbers between 0 and 10 of size (7, 2)
    * Create an array of normally distributed random numbers
    * Create an array of 20 numbers of a Beta distribution with parameters 0.2 and 0.5
    * Create an array of 100 numbers of a Binomial distribution with parameters 0.5
    * Create a matrix of 3x3x3 with np.random.random


In [23]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

In [24]:
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
                [4, 5, 6]])

In [25]:
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [26]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [27]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[1, 6],
       [1, 2],
       [8, 9],
       [6, 4],
       [4, 8],
       [8, 8],
       [3, 9]])

* Create an array of normally distributed random numbers

In [30]:
randn = np.random.randn(10)
randn

array([ 1.00518482,  1.7188176 ,  1.16057521, -0.68248057,  0.26352791,
        0.49404848,  0.57950401, -2.67505221, -1.26770356, -1.34064672])

* Create an array of 20 numbers of a Beta distribution with parameters 0.2 and 0.5

In [31]:
beta = np.random.beta(0.2, 0.5, 10)
beta

array([4.78233691e-01, 4.32122621e-04, 8.77070018e-01, 1.04405386e-03,
       6.41872431e-01, 4.48435951e-03, 9.45919313e-07, 5.52022379e-01,
       5.54846623e-01, 2.73146131e-01])

* Create an array of 100 numbers of a Binomial distribution with parameters 0.5

In [32]:
binomial = np.random.binomial(10, 0.5, 10)
binomial

array([5, 4, 6, 6, 6, 5, 4, 4, 1, 6])

* Create a matrix of 3x3x3 with np.random.random

In [33]:
my_array = np.random.random((3, 3, 3))
my_array

array([[[0.85219945, 0.43402141, 0.88947546],
        [0.36294029, 0.28355433, 0.48875951],
        [0.89194731, 0.14493895, 0.88190529]],

       [[0.54314788, 0.37728041, 0.81570396],
        [0.52658318, 0.06368654, 0.79808997],
        [0.42628866, 0.0108255 , 0.91427146]],

       [[0.20396471, 0.27212036, 0.98652557],
        [0.22434271, 0.36842623, 0.3444986 ],
        [0.32950887, 0.23909552, 0.79442917]]])